### ISSUE TITLE
rating change & performance is strange

### ISSUE THREAD

**Issue by jwvg0425** [sono8stream/codeforces-anytime#26]
https://codeforces-anytime.firebaseapp.com/users/2K1mQrBOTVeXnihcEDto9mRa3Ei2

this is my profile. I get 163th in my last virtual codeforces contest, and it says my performance was 2318. but in official contest, rank 162th(olphe)'s rating changes from 2394 to 2415. then, 162th's performance is higher than 2400, and 163th's performance is 2318. I think this performance gap is so huge.

how to calculate performance & rating change in this site?

**Comment by sono8stream** [comment]
Thank you for using my app and reporting the problem.

This app calculates rating changes by using algorithm mentioned [here](https://codeforces.com/blog/entry/20762).

Also, performance is calculated to be almost equal to  ***R*** in this algorithm. In other words, performance is (old rating) + (rating delta) * 2.

And the implementation of rating change is [here](https://github.com/sono8stream/codeforces-anytime/blob/8697b75f04c50609dd096600ed9b06d99f46b2f5/src/actions/index.ts#L59).

Anyway, The implementation may be incorrect, so please give me time to confirm.

**Comment by sono8stream** [comment]
I implemented test code and it indicated that the algorithm of rating change is as same as the one in original Codeforces.

But, the performance is not equal to usual calculation algorithm. The performance should be almost  **(old rating) + (rating delta) * 4**.

So, I fixed that performance calculation algorithm and the updated version will be deployed later.

**Comment by jwvg0425** [comment]
thank you for investigation!

I think performance value should be like below:

if one has rating X ranked Y in the contest and his rating will not change, then rank Y's performance value is X. for example, in Round # 669, 1101th's rating does not change(https://codeforces.com/contest/1407/ratings/page/12). so, 1101th's performance would be 1877.

but if this type of calculation is so hard to implement or impossible, using current formula( **(old rating) + (rating delta) * 4** ) is also good enough.

**Comment by sono8stream** [comment]
Yes, I think you are correct.

The performance will be the most likely rating when a user is at a rank.

I can calculate this value when calculating rating change but it is difficult to add this parameter column in the DB currently.

So tentatively, I use the shown formula to display performance on the browser and don't save them in the DB.

Finally, I deployed the fixed version of this app. Thank you.

**Comment by jwvg0425** [comment]
ah, ok. I understand it. thank you for fix!
