### ISSUE TITLE
Team practice is included in the rating.

### ISSUE THREAD

**Issue by JooDdae** [sono8stream/codeforces-anytime#30]
https://codeforces-anytime.firebaseapp.com/users/JA9yLJSGLvS82CBPtcfGnoJdqrf1

This is my profile. The contest in GYM which I solved in team and it is included in my rating.
https://codeforces.com/gym/101669
https://codeforces.com/gym/102082
These two link are the contest which is the problem.

I update my history only if I run a virtual contest.
please check about it.

**Comment by sono8stream** [comment]
Sorry for my very late reply.

I'll check this problem.

**Comment by sono8stream** [comment]
Fixed.
