### ISSUE TITLE
単一のコンテスト結果が複数回反映される

### ISSUE THREAD

**Issue by tsutaj** [sono8stream/codeforces-anytime#4]
https://twitter.com/ta1sa_/status/1247181178508959744

単一のバーチャルコンテストの結果が複数回反映されていそうな挙動があります。
とりあえず不具合報告です

**Comment by sono8stream** [comment]
確認しますー

**Comment by sono8stream** [comment]
これ，レート計算をフロントで処理していて，複数同時に走っちゃってるのが問題っぽい
とりあえず書き込む直前に他の処理によって変更されていないかチェックするようにして対処
完璧ではないのでどこかで根本的に直す必要あり
